info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
        - 首页
  /user/Update:
    put:
      parameters:
        - description: id
          in: body
          name: id
          required: true
          schema:
            type: integer
        - description: 用户名
          in: body
          name: name
          required: true
          schema:
            type: string
        - description: 密码
          in: body
          name: pass_word
          required: true
          schema:
            type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: json
      tags:
        - 更新用户
  /user/create:
    post:
      parameters:
        - description: 用户名
          in: body
          name: name
          required: true
          schema:
            type: string
        - description: 密码
          in: body
          name: pass_word
          required: true
          schema:
            type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: json
      tags:
        - 创建用户
  /user/delete/{id}:
    delete:
      parameters:
        - description: 用户信息
          in: path
          name: id
          required: true
          type: integer
      responses:
        "200":
          description: code","message"}
          schema:
            type: json
      tags:
        - 删除用户
  /user/getUserList:
    get:
      responses:
        "200":
          description: code","message"}
          schema:
            type: json
      tags:
        - 获取用户列表
swagger: "2.0"
